language: python
sudo: required
branches:
  # blacklist
  except:
    - 1-3-maint
#  only:
#  - ansible_1.9.2

#services:
#  - docker
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install build-essential libtool autoconf
script:
  # Run tests on Ubuntu 12
  -  ./autogen.sh && ./configure && make &&  make install